id = "poimandres-v2"
name = "poimandres-v2"
version = "0.0.1"
schema_version = 1
authors = [
    "mshaugh <max@mshaugh.com>",
    "stevedylandev <stevedsimkins@gmail.com>",
]
description = "poimandres themes"
repository = "https://github.com/stevedylandev/poimandres.zed"
